sudo: false
language: c

addons:
  apt:
    packages:
      - check

script:
        - cd ./tests
        - make coverage

after_success:
          - bash <(curl -s https://codecov.io/bash)

notifications:
        email: false
